"use client";

import { Header } from "@/components/header";
import { UserContextProvider } from "@/context/userContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toast, ToastProvider } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ToastProvider>
      <UserContextProvider>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            {children}
            <Toaster/>
          </body>
        </html>
      </UserContextProvider>
    </ToastProvider>
  );
}
